name: install RSI
on: [push]
jobs:
  install_ubuntu:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      COLORTERM: truecolor
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ run bash rsi.sh --yes"
      - name: run RSI install
        run: |
          bash rsi.sh --yes
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  install_macos:
    runs-on: macos-latest
    env:
      TERM: xterm-256color
      COLORTERM: truecolor
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ run bash rsi.sh --yes"
      - name: run RSI install
        run: |
          bash rsi.sh --yes
      - run: echo "ğŸ This job's status is ${{ job.status }}."